### PR TITLE
cmd - invalid response

### LINKED ISSUE #161: iis_section unlock fails to unlock authentication section
In my cookbook I'm trying to unlock the IIS windowsAuthentication and anonymousAuthentication sections at the global level but somehow it is not working correctly. I'm running the cookbook against a Win2012R2 server and am installing IIS with the IIS cookbook (version 4.1.0):

    include_recipe 'iis'
    
    # Install the ASP.NET 4.5 runtime components
    include_recipe 'iis::mod_aspnet45'
    
    # Install the Windows authentication support
    include_recipe 'iis::mod_auth_windows'
    
    # install the HTTP logging, logging tools and custom logging
    include_recipe 'iis::mod_logging'
    
    # remove the default website
    include_recipe 'iis::remove_default_site'

All of that is working successfully.

The code in my cookbook to unlock the authentication sections is:

    iis_section 'system.webServer/security/authentication/anonymousAuthentication' do
      action :unlock
      section 'system.webServer/security/authentication/anonymousAuthentication'
    end
    
    iis_section 'system.webServer/security/authentication/windowsAuthentication' do
      action :unlock
      section 'system.webServer/security/authentication/windowsAuthentication'
    end

The cookbook runs to completion but the sections are just not unlocked.

I also have unlock sections for

    iis_section 'system.webServer/handlers' do
      section 'system.webServer/handlers'
      action :unlock
    end
    
    iis_section 'system.webServer/modules' do
      section 'system.webServer/modules'
      action :unlock
    end

These seem to be working correctly but the authentication section is not working. If I unlock the sections manually then it works. Like this:

    powershell_script 'unlock IIS authentication sections' do
      code <<-POWERSHELL
        $ErrorActionPreference = 'Stop'
    
        $appCmd = 'c:\\windows\\system32\\inetsrv\\appcmd.exe'
    
        & $appCmd unlock config -section:"system.webServer/security/authentication/anonymousAuthentication" -commit:apphost
        & $appCmd unlock config -section:"system.webServer/security/authentication/windowsAuthentication" -commit:apphost
      POWERSHELL
    end

From looking at the iis_section unlock code I think the `-commit:apphost` bit is missing (see http://serverfault.com/a/360556/239001)?

### PR DESCRIPTION
**Pull request by EasyAsABC123**
this is causing the command to fail and thereby always throw invalid results

attempt to resolve #161

### CODE REVIEW

File: providers/section.rb [hunk 1]
```diff
@@ -28,7 +28,7 @@
 action :lock do
   @current_resource.exists = new_value?(doc.root, 'CONFIG/@overrideMode', 'Deny')
 
-  if !@current_resource.exists
+  if @current_resource.exists
```
Comment (ksubrama) [inline providers/section.rb]: I think the confusion occurred because we're using @current_resource.exists (which is meant to signify if the resource exists) to actually mean "is the resource unlocked".  We should probably clean this up (at some nebulous time in the future).

**Comment by ksubrama** [comment]
:+1:
